In [1]:
import pandas as pd
import numpy as np
import random as rd
import seaborn as sns
from sklearn.decomposition import NMF
from random import random
import matplotlib.pyplot as plt

In [2]:
my_data=pd.read_csv('all_data_filtered.csv')
my_data.head(10)
my_data.index=my_data['Patient_id']

In [55]:
my_data=my_data.drop(['Patient_id'],axis=1)
my_data.head()

ENSG00000223972  ENSG00000227232  ENSG00000243485  \
Patient_id                                                      
165-06             0.000000        24.743294              0.0   
031-31             0.000000        18.281501              0.0   
069-02             0.062838        32.815619              0.0   
007-08             0.000000        17.226358              0.0   
034-24             0.000000        13.274798              0.0   

            ENSG00000268020  ENSG00000240361  ENSG00000186092  \
Patient_id                                                      
165-06                  0.0              0.0              0.0   
031-31                  0.0              0.0              0.0   
069-02                  0.0              0.0              0.0   
007-08                  0.0              0.0              0.0   
034-24                  0.0              0.0              0.0   

            ENSG00000238009  ENSG00000233750  ENSG00000237683  \
Patient_id                                                      
165-06             0.015504         0.029030         0.249525   
031-31             0.000000         0.087378        11.042994   
069-02             0.000000         0.361829        27.015709   
007-08             0.000000         0.018849         1.107071   
034-24             0.031994         0.039939         0.171643   

            ENSG00000268903  ...  ENSG00000244656  ENSG00000263760  \
Patient_id                   ...                                     
165-06             0.000000  ...              0.0              0.0   
031-31             1.078417  ...              0.0              0.0   
069-02             3.799909  ...              0.0              0.0   
007-08             0.190335  ...              0.0              0.0   
034-24             0.000000  ...              0.0              0.0   

            ENSG00000264728  ENSG00000238667  ENSG00000238477  \
Patient_id                                                      
165-06             2.666607         1.999955         0.674782   
031-31             0.000000         0.000000         0.000000   
069-02             0.000000         2.658880         2.018479   
007-08             0.000000         0.000000         0.000000   
034-24             0.000000         0.000000         0.000000   

            ENSG00000271726  ENSG00000215616  ENSG00000265557  \
Patient_id                                                      
165-06                  0.0              0.0              0.0   
031-31                  0.0              0.0              0.0   
069-02                  0.0              0.0              0.0   
007-08                  0.0              0.0              0.0   
034-24                  0.0              0.0              0.0   

            ENSG00000238643  MRD Response  
Patient_id                                 
165-06                  0.0           0.0  
031-31                  0.0           1.0  
069-02                  0.0           1.0  
007-08                  0.0           0.0  
034-24                  0.0           1.0  

[5 rows x 53967 columns]

In [56]:
y=my_data['MRD Response']
X=my_data.drop(['MRD Response'],axis=1)

In [57]:
X.shape

(491, 53966)

In [58]:
CorrPatients=np.corrcoef(my_data)
#CorrGenes=np.corrcoef(my_data.T)

In [61]:
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from scipy.spatial.distance import squareform

plt.figure(figsize=(12,5))
dissimilarity = 1 - abs(CorrPatients)
print(dissimilarity.shape)
Z = linkage(squareform(X=dissimilarity), 'complete')

dendrogram(Z, X.columns, orientation='top', 
           leaf_rotation=90)

(491, 491)


ValueError: Distance matrix 'X' must be symmetric.

<Figure size 1200x500 with 0 Axes>

In [51]:
n_samples=X.shape[0]
n_genes=X.shape[1]

In [49]:
class nmf_model(X):
    def __init__(self) -> None:
        self.data=X
    
    def eval_one_model(X,n_components):
        model=NMF(n_components,init='random')
        C_all_runs=np.zeros((n_samples,n_samples))
        while ... :
            W=model.fit_transform(X)
            H=model.components_
            n_metagenes=H.shape[0]
            #calculate Connectivity matrix
            clusters=np.zeros(n_samples)
            C=np.zeros((n_samples,n_samples))
            for i in range (n_samples):
                clusters[i]=np.argmax(H[:,i])
            for i in range (n_samples):
                for j in range (i,n_samples):
                    if (clusters[i]==clusters[j]):
                        C[i,j]=1
                    else:
                        C[i,j]=0
            C_all_runs=C_all_runs+C
            return C_all_runs/n_runs
        
    def model_selection():
        list_param=[10,100,1000,10000]
        C_k=[]
        for k in list_param:
            C_k.append(eval_one_model(X,k))
        return C_k
    



TypeError: 'str' object cannot be interpreted as an integer

In [58]:
def nmf (X,n_components,n_runs):
    model =NMF(n_components=100, init="random", random_state=0)
    C_all_runs=np.zeros((n_samples,n_samples))
    for n in range (n_runs):
        W=model.fit_transform(X)
        H=model.components_
        n_metagenes=H.shape[0]
        #calculate Connectivity matrix
        clusters=np.zeros(n_samples)
        C=np.zeros((n_samples,n_samples))
        for i in range (n_samples):
            clusters[i]=np.argmax(H[:,i])
        for i in range (n_samples):
            for j in range (i,n_samples):
                if (clusters[i]==clusters[j]):
                    C[i,j]=1
                else:
                    C[i,j]=0
        C_all_runs=C_all_runs+C
        return C_all_runs/n_runs

In [60]:
def nmf_selection(X,n_runs,k_list):
    C_k=[]
    for k in k_list:
        C_k.append(nmf(X,k,n_runs))
    return C_k
    

In [62]:
nmf_selection(X,5,[10,100,1000])

/home/irit/.local/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(
/home/irit/.local/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(
/home/irit/.local/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


[array([[0.2, 0. , 0. , ..., 0.2, 0. , 0. ],
        [0. , 0.2, 0. , ..., 0. , 0.2, 0.2],
        [0. , 0. , 0.2, ..., 0. , 0. , 0. ],
        ...,
        [0. , 0. , 0. , ..., 0.2, 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0.2, 0.2],
        [0. , 0. , 0. , ..., 0. , 0. , 0.2]]),
 array([[0.2, 0. , 0. , ..., 0.2, 0. , 0. ],
        [0. , 0.2, 0. , ..., 0. , 0.2, 0.2],
        [0. , 0. , 0.2, ..., 0. , 0. , 0. ],
        ...,
        [0. , 0. , 0. , ..., 0.2, 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0.2, 0.2],
        [0. , 0. , 0. , ..., 0. , 0. , 0.2]]),
 array([[0.2, 0. , 0. , ..., 0.2, 0. , 0. ],
        [0. , 0.2, 0. , ..., 0. , 0.2, 0.2],
        [0. , 0. , 0.2, ..., 0. , 0. , 0. ],
        ...,
        [0. , 0. , 0. , ..., 0.2, 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0.2, 0.2],
        [0. , 0. , 0. , ..., 0. , 0. , 0.2]])]

In [44]:
import numpy as np
from sklearn.decomposition import NMF
from scipy.spatial.distance import pdist
from scipy.cluster.hierarchy import linkage, cophenet

# Generate some sample data
X = np.random.rand(100, 10)
# Apply NMF to the data
model = NMF(n_components=2, init='random', random_state=0)
X = model.fit_transform(X)
H=model.components_
# Calculate pairwise distance matrix
dist_matrix = pdist(X)
print(dist_matrix)
# Apply hierarchical clustering
linkage_matrix = linkage(dist_matrix, method='ward')
# Calculate cophenetic correlation coefficient
coph_corr, coph_dist = cophenet(linkage_matrix, dist_matrix)

print("Cophenetic correlation coefficient:", coph_corr)

[0.12858969 0.26749319 0.25900064 ... 0.36426651 0.2064698  0.20678569]
Cophenetic correlation coefficient: 0.6318492580993474


In [ ]:
# Apply hierarchical clustering
linkage_matrix = linkage(dist_matrix, method='ward')